[package]
name = "mygit"
version = "0.1.0"
authors = ["yameholo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.8.2"
flate2 = "1.0.14"
